### PR TITLE
Analyze metafiles

### LINKED ISSUE #48: Analyze bundle contents
Add a feature to `builder` that allows for the analysis and reporting of bundle contents:

1. Write out metafile.json file when creating bundles
2. Print out summary analysis of metafile in textual form

### PR DESCRIPTION
**Pull request by carlansley**
Fixes #48

### CODE REVIEW

**Comment by carlansley** [comment]
Basic support added.  Currently for bundles all `builder` does is output something like:
```
test/index.test.mjs: src 3773, node_modules 280920, total 285936
```
If you want a more detailed breakdown, you can visualize the metafile.json here: https://esbuild.github.io/analyze/

**Comment by carlansley** [comment]
@adcreare (post Davastation) will create an action that uses this to make a comment in PRs letting people know
a) their code can be built as a bundle with `builder` and
b) how big the bundle is.

**Review by ramaghanta — CHANGES_REQUESTED** [review]

**Review by ramaghanta — APPROVED** [review]
lgtm

**Review by le-cong — APPROVED** [review]
lgtm

**Review by adcreare — APPROVED** [review]
LGTM - I've noted the action work needed.

**Pull request merged**
