### PR TITLE
Support Typescript 5.7

### LINKED ISSUE #67: Support Typescript 5.7

### LINKED ISSUE #69: Require new Node minimum version (22)

### PR DESCRIPTION
**Pull request by carlansley**
Fixes #67
Fixes #69

### CODE REVIEW

**Comment by carlansley** [comment]
gtg once https://github.com/typescript-eslint/typescript-eslint/issues/10115 is resolved

**Review by le-cong — APPROVED** [review]
lgtm

**Review by ramaghanta — APPROVED** [review]
lftm

**Review by adcreare — APPROVED** [review]
LGTM

**Pull request merged**
