### PR TITLE
Update to Typescript 5.1, drop Node 16

### LINKED ISSUE #37: Support Typescript 5.1
https://devblogs.microsoft.com/typescript/announcing-typescript-5-1/

### LINKED ISSUE #39: Make Node 18 the minimum supported version

### PR DESCRIPTION
**Pull request by carlansley**
Fixes #37
Fixes #39

### CODE REVIEW

**Comment by carlansley** [comment]
Will stay in draft until typescript-eslint gets update to remove this error:
```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.1.0

YOUR TYPESCRIPT VERSION: 5.1.3

Please only submit bug reports when using the officially supported version.

=============

```
Fortunately no major syntax changes, so prettier/IDE/etc support should be fine.

**Comment by carlansley** [comment]
waiting on https://github.com/typescript-eslint/typescript-eslint/issues/6934

**Comment by carlansley** [comment]
note: there is a bug in typescript 5.1.3 causing an OOM for `typescript-eslint` tests.  Will be fixed in Typescript 5.1.4, after which whenever a new typescript-eslint is released we'll be good-to-go.

**Comment by carlansley** [comment]
Updated to Typescript 5.1.6 and the latest `typescript-eslint`, warning is now gone.

**Review by ramaghanta — APPROVED** [review]

**Pull request merged**
